# Generated by Django 4.2.8 on 2025-01-25 20:50

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("empresas", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("descripcion", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Presentacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_presentacion", models.CharField(max_length=50)),
                ("cantidad", models.PositiveIntegerField()),
                ("precio", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "porcentaje_adicional",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Porcentaje adicional a aplicar al precio (0-100).",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
            ],
            options={
                "verbose_name": "Presentación",
                "verbose_name_plural": "Presentaciones",
            },
        ),
        migrations.CreateModel(
            name="Sucursal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200, unique=True)),
                ("direccion", models.TextField()),
                ("telefono", models.CharField(max_length=20)),
                (
                    "codigo_establecimiento",
                    models.CharField(blank=True, max_length=3, null=True),
                ),
                (
                    "punto_emision",
                    models.CharField(blank=True, max_length=3, null=True),
                ),
                ("es_matriz", models.BooleanField(default=False)),
                (
                    "secuencial_actual",
                    models.CharField(default="000000000", max_length=9),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sucursales",
                        to="empresas.empresa",
                    ),
                ),
                (
                    "usuarios",
                    models.ManyToManyField(
                        related_name="sucursales", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("producto", "Producto"), ("servicio", "Servicio")],
                        default="producto",
                        max_length=20,
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("descripcion", models.TextField(blank=True, null=True)),
                (
                    "unidad_medida",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "codigo_producto",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="productos/"),
                ),
                ("stock_minimo", models.IntegerField(default=0)),
                ("activo", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "categoria",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="productos",
                        to="core.categoria",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="productos",
                        to="empresas.empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Producto",
                "verbose_name_plural": "Productos",
            },
        ),
    ]
