# Generated by Django 4.2.8 on 2025-01-25 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("facturacion", "0001_initial"),
        ("empresas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="impuesto",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="productos",
                to="facturacion.impuesto",
            ),
        ),
        migrations.AddField(
            model_name="producto",
            name="sucursales",
            field=models.ManyToManyField(
                blank=True, related_name="productos", to="core.sucursal"
            ),
        ),
        migrations.AddField(
            model_name="presentacion",
            name="producto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="presentaciones",
                to="core.producto",
            ),
        ),
        migrations.AddField(
            model_name="presentacion",
            name="sucursal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="presentaciones",
                to="core.sucursal",
            ),
        ),
        migrations.AddField(
            model_name="categoria",
            name="empresa",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categorias",
                to="empresas.empresa",
            ),
        ),
        migrations.AddIndex(
            model_name="sucursal",
            index=models.Index(
                fields=["empresa"], name="core_sucurs_empresa_2f4cbc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sucursal",
            index=models.Index(
                fields=["codigo_establecimiento", "punto_emision"],
                name="core_sucurs_codigo__0fbac6_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="sucursal",
            unique_together={("codigo_establecimiento", "punto_emision")},
        ),
        migrations.AlterUniqueTogether(
            name="producto",
            unique_together={("empresa", "nombre")},
        ),
        migrations.AlterUniqueTogether(
            name="categoria",
            unique_together={("empresa", "nombre")},
        ),
    ]
