# Generated by Django 4.2.8 on 2025-02-04 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ventas", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="venta",
            name="cantidad",
            field=models.PositiveIntegerField(),
        ),
    ]
