# Generated by Django 4.2.8 on 2025-01-25 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RegistroTurno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("inicio_turno", models.DateTimeField()),
                ("fin_turno", models.DateTimeField(blank=True, null=True)),
                (
                    "total_ventas",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total_efectivo",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "otros_metodos_pago",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
            ],
        ),
    ]
