# Generated by Django 4.2.8 on 2025-01-25 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("compras", "0001_initial"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="detallecompra",
            name="producto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.producto"
            ),
        ),
        migrations.AddField(
            model_name="compra",
            name="proveedor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="compras.proveedor",
            ),
        ),
        migrations.AddField(
            model_name="compra",
            name="sucursal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.sucursal"
            ),
        ),
        migrations.AddConstraint(
            model_name="compra",
            constraint=models.UniqueConstraint(
                fields=("sucursal", "fecha_emision"),
                name="unique_sucursal_fecha_emision",
            ),
        ),
    ]
